[package]
authors = []
edition = "2021"
name = "lingua_nif"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
name = "lingua_nif"
path = "src/lib.rs"

[dependencies]
lingua = "1.5.0"
rustler = "0.36"
 
